---
# tasks file for ansible-role-apt-install-then-clean

- name: install packages
  apt:
    state: "{{ state }}"
    update_cache: "{{ update_cache }}"
    autoremove: "{{ autoremove }}"
    pkg: "{{ packages }}"
  register: packages_installed

- name: debug packages_installed
  debug:
    var: packages_installed
  when: packages_installed.changed

# TODO: move this to handlers
- name: clean /var/cache/apt/archives/*.deb
  command: apt-get clean
  args:
    # ansible warns user to use the ansible apt module  for a feature
    # that is not implemented by the ansible apt module.
    warn: no
  when: packages_installed.changed
  changed_when: false
  
    
